services:
  - type: web
    name: money-splitter-frontend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    repo: https://github.com/NikhilBaswal/Money_Splitter_App
    branch: main
    rootDir: . # this is important if everything is in root
