services:
  - type: web
    name: money-splitter-frontend
    env: node
    repo: https://github.com/NikhilBaswal/Money_Splitter_App
    branch: main
    buildCommand: npm install && npm run build
    startCommand: npm start
    rootDir: . # root for frontend (Next.js)

  - type: web
    name: money-splitter-backend
    env: node
    repo: https://github.com/NikhilBaswal/Money_Splitter_App
    branch: main
    buildCommand: cd backend && npm install && npm run build
    startCommand: cd backend && npm run start:prod
    rootDir: backend
