services:
  - type: web
    name: money-splitter-frontend
    env: node
    buildCommand: npm install --omit=dev=false && npm run build
    startCommand: npm start
    repo: https://github.com/NikhilBaswal/Money_Splitter_App
    branch: main
    rootDir: .
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://backend-2vqx.onrender.com

  - type: web
    name: money-splitter-backend
    env: node
    buildCommand: npm install --omit=dev=false && npm run build
    startCommand: npm run start:prod
    repo: https://github.com/NikhilBaswal/Money_Splitter_App
    branch: main
    rootDir: backend
    envVars:
      - key: PORT
        value: 10000 # or leave blank for Render to assign
      - key: SUPABASE_URL
        value: https://supabase.com/dashboard/project/rrqykrmyhpxrfdhlzuon
      - key: SUPABASE_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJycXlrcm15aHB4cmZkaGx6dW9uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0Nzg0NzMsImV4cCI6MjA3MDA1NDQ3M30.H92VUXwI9_7yCQPzM9TEij0eq2gE71Wc_W1hI4Ltz3k
      - key: DATABASE_URL
        value: postgresql://postgres:admin@123@db.rrqykrmyhpxrfdhlzuon.supabase.co:5432/postgres
      # Add any other backend env vars here
